### PR TITLE
Fix contains and containsonly implementation along with tests

### PR DESCRIPTION
**Pull request by kapishmalik**
…tests

### CODE REVIEW

**Review by tommysitu — COMMENTED** [review]
I wonder what happened if you compare two empty array could you add a test for that please?

**Comment by kapishmalik** [comment]
> I wonder what happened if you compare two empty arrays could you add a test for that please?

@tommysitu addressed this comment.

**Review by tommysitu — APPROVED** [review]
Thanks, LGTM

**Comment by kapishmalik** [comment]
@tommysitu you can merge this PR.

**Pull request merged**
