### PR TITLE
fix: update go path for major version update

### PR DESCRIPTION
**Pull request by joobus**
The upgrade to v2.0.0 was not done properly and now v2 is not importable by any other programs.

[See similar issue here](https://stackoverflow.com/questions/58066548/installing-a-go-module-fails-with-invalid-module-contains-a-go-mod-file-so-ma).

[See Go wiki here](https://github.com/golang/go/wiki/Modules#semantic-import-versioning)

After merging this PR, you will need to make a patch release (v2.0.1) so that this library is importable again.

My main use-case is that I have written middleware in Go for hoverfly, and have imported the middleware request/response structures into my middleware, but now can't upgrade to v2 because of this issue.

This PR addresses https://github.com/SpectoLabs/hoverfly/issues/1060

### CODE REVIEW

**Comment by tommysitu** [comment]
Oh no, my bad. @joobus I'm thinking to remove the v2 release and re-do it as v1.5.0 instead, because it's still backwards compatible. What do you think?

**Comment by joobus** [comment]
@tommysitu I would support that.  Sticking to [semantic versioning](https://semver.org/) is a good idea.

**Comment by tommysitu** [comment]
thanks, I will fix the versioning issue.

**Comment by tommysitu** [comment]
this is fixed now: https://github.com/SpectoLabs/hoverfly/releases/tag/v1.5.0

sorry for the confusion.

**Pull request closed without merging**
