### PR TITLE
Added feature for matching query params with multiple values with new matchers

### PR DESCRIPTION
**Pull request by kapishmalik**
Added features for matching multiple with multiple values with newly introduced matchers containsexactly, containsonly, contains.

containsexactly - Verifies that the actual group contains exactly the given values and nothing else, in order.

containsonly - Verifies that the actual group contains only the given values and nothing else, in any order and ignoring duplicates (i.e. once a value is found, its duplicates are also considered found).

contains - Verifies that the actual group contains the given values, in any order.

All of the above matchers are case-sensitive. On saving simulation, we are saving as containsexactly as default value.

Implemented as described in the comment - https://github.com/SpectoLabs/hoverfly/issues/842#issuecomment-497652641

### CODE REVIEW

**Comment by kapishmalik** [comment]
Resolves #842

**Review by tommysitu — APPROVED** [review]
Top-notch! love the tests 👍

**Comment by tommysitu** [comment]
btw @kapishmalik you haven't set up your git email config properly, we can't really see you as a contributor for this commit.

**Comment by kapishmalik** [comment]
@tommysitu is there a way now to correct this?

**Comment by tommysitu** [comment]
looks like you have fixed it

**Comment by kapishmalik** [comment]
I have fixed while raising other PR but not for this commit.

**Pull request merged**
