### PR TITLE
Added ProxyFromEnvironment configuration option 

### PR DESCRIPTION
**Pull request by Bruno-DaSilva**
This should allow auto proxy configuration based off of http_proxy/https_proxy and no_proxy environment variables, referenced in issue #373

### CODE REVIEW

**Comment by benjih** [comment]
Hey @Bruno-DaSilva,

The common usage of Hoverfly is set the HTTP_PROXY and HTTPS_PROXY environment variables to the address of Hoverfly.  This is something suggested to users in our documentation as well as being something our functional tests do.

As a result of this, this breaks functional tests by causing a proxying loop when the HTTP_PROXY and HTTPS_PROXY variables are set to Hoverfly.

There are two possible solutions to this.

The first is to implement some kind of check to make sure that those variables are not set to point to Hoverfly before setting the default HTTP client's proxy settings.

The second is to have proxy as a startup flag on the Hoverfly binary `core/hoverfly/cmd/main.go` which is then passed through GetNewHoverfly() and into GetDefaultHoverflyHTTPClient(). This startup flag could then be added to Hoverctl, providing the same functionality as this change, but more as a configuration.

I think the second option is more work, but it makes sense. If you are running behind a proxy but you wanted to put Hoverfly infront of that, you should be setting HTTP_PROXY and HTTPS_PROXY to Hoverfly and then telling Hoverfly that their is a proxy between itself and its intended destination.

I'm interested to hear your thoughts.

I'm interested to hear your opinion

**Comment by Bruno-DaSilva** [comment]
Hey @benjih, you certainly bring up an excellent point. I've been looking at this from my own perspective only, where we use docker containers to isolate our services (and so there would not be conflicts with environment variables). You are right, though, that this does pose a problem for the larger user base and the solution I've offered thus far would potentially mean more work/confusion for them.

With regards to your first solution, while it could work, I do see a rather large problem with it. How does hoverfly know that the HTTP_PROXY env variable is pointing to itself? Does it send an http request to whatever it is set to in order to verify if it is actually pointing to a hoverfly instance? What happens if you're trying to chain multiple hoverflys together (it's a rather edge case circumstance but it _could_ happen), how would you know that the hoverfly you get a response back is yourself?

The second option, however, is much more explicit and less brittle in my opinion. You will avoid the 'autodetection' issue entirely, and give users full control of having a proxy setting enabled or disabled. There are two ways to do this in my opinion:
- have simply a true/false flag as an option which just takes from the env variables
- have an explicit setting somewhere (command line/config file; proxy_host: test.host.proxy.com, proxy_port: 443). It would require more implementation but would allow users to be explicit with their proxy settings without having to set or change an environment variable. 

Now, I think the second option is without a doubt the best solution of the two. My only question is which way to go (true/false vs explicit config) do you think is the better solution? I can take a crack at whichever you think is best.

**Comment by benjih** [comment]
I think having it as an explicit option would be best and then have main.go pass it through on construction of a new Hoverfly instance via the config. Putting the proxy address in config seems appropriate to me.

**Comment by Bruno-DaSilva** [comment]
Oh perfect, implementing that in hoverctl would have been my next question. I'll get on that :)

**Comment by Bruno-DaSilva** [comment]
Hey @benjih, I've made the changes and updated the pull request (it's a super small change).

I'm new to golang so I'm sure there's some conventions I'm breaking. I'm open to any feedback as to what is missing/should be changed.

**Comment by benjih** [comment]
Just had a looking at the pull request and its looking great!

I spoke to a few of the people here and we had a bit of a debate as to whether or not the `external-proxy` flag was clear enough. Someone mentioned that it might cause some confusion as external could have several meanings depending on the situation.

An idea was suggested to rename it to `upstream-proxy` as this was a bit cleare. If you configure a second proxy in a chain of proxies, you can only link them by configuring a proxy with an upstream proxy location.

I'm interested to hear your thoughts in the matter.

Other than that, all good. I await your response and any changes required and then I will merge this in.

Thank you very much @Bruno-DaSilva.

**Comment by Bruno-DaSilva** [comment]
@benjih Thanks for taking a look so fast. You're definitely right that it's not clear enough, I was struggling to find a succinct flag to describe what it actually did. `upstream-proxy` sounds much better, I'll make that change.

**Pull request merged**
