### PR TITLE
Body files remote

### LINKED ISSUE #951: Allow for remote bodyFiles
**Is your feature request related to a problem? Please describe.**
I want to be able to run hoverfly locally, but load remote simulations. This is possible using `--import` but bodyFiles cannot be loaded remotely. I want to do this so that third-party contributors can work off of the same set of simulations.

**Describe the solution you'd like**
Just like with `--import`, I would like to be able to reference remote bodyFiles.

**Describe alternatives you've considered**
One alternative would be to write a tool to load files and inject JSON strings into simulation files and load those remotely.

### PR DESCRIPTION
**Pull request by ns3777k**
Closes #951

### CODE REVIEW

**Comment by tommysitu** [comment]
The changes look good to me. The only concern is that this feature might introduce a security issue if someone gains access to an external facing hoverfly instance, and they can use remote body file to fetch information from internal network. Convenience comes with risks. Any suggestion? Perhaps make it disabled unless you pass a start-up flag to switch on?

**Comment by ns3777k** [comment]
hmmm. interesting catch 🧐 it can be a startup flag, or a little complex solution to have a whitelist for base urls (for protocol checking) / hostnames?

example for base urls:

```shell
$ hoverfly --allow-remote-body-file-origin=https://raw.githubusercontent.com:1234
```

or hostnames:

```shell
$ hoverfly --allow-remote-body-file-origin=raw.githubusercontent.com:1234
```

@tommysitu

**Comment by tommysitu** [comment]
yeah that's a good idea 💡  I will go for matching both schema and hostname like CORS: `$ hoverfly --allow-remote-body-file-origin=https://raw.githubusercontent.com:1234`. To use this feature, user needs to pass this setting to avoid accidentally turning it on, and the file can only be fetched from the allow origin.

**Comment by ns3777k** [comment]
@tommysitu done

**Review by tommysitu — APPROVED** [review]
It looks great! 👍

**Pull request merged**
